version: '0.1'

services:
  backend:
    container_name: nestjs-backend
    build: .
    ports:
      - '3232:3232'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    container_name: nestjs-postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata:
